language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.0.5.0

notifications:
  email:
    on_success: never

sudo: false

before_install:
  - gem install bundler -v "~> 1.0"

script:
  - bundle exec rake